# Generated by Django 2.1 on 2019-03-20 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_auto_20181017_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor_detail',
            name='specialization',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
