# Generated by Django 2.1.1 on 2018-10-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='awards',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='report_link',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student2_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student2_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student3_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student3_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student4_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student4_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student5_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='student5_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='tools_used',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
